
# This is the main Supabase configuration file for serverless edge functions
project_id = "neighborhood-dashboard"

[global.env_variables]
# Leave this empty, secrets will be managed through Supabase dashboard

[functions]
[functions.notify-skills-changes]
verify_jwt = true

# The notify-neighbor-changes function is now deprecated
# We use database triggers instead for better performance and reliability
[functions.notify-neighbor-changes]
verify_jwt = true
enabled = false  # Disabled as functionality moved to database triggers
